### ISSUE TITLE
Rename provision-vm to provision-vagarant

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-deploy#10]
Please rename the files provision-vm to something like provision-vagrant.

Currently the OpenConext deploy only focusses on vagrant and test. Also it requires a Mac to install.
To remove the Mac requirement and allow installation of an OpenConext-environment on an separate VM (without Vagrant) the name provision-vm might be used in the future.

It also clarifies what the files/script are meant for.

**Comment by thijskh** [comment]
The confusion stems from the use of the term "vm" as shorthand for "OpenConext-vm" (a specific idea of an OpenConext install for trial and testing), not for "any virtual machine".

But renaming it makes it less ambiguous to be sure.
