### ISSUE TITLE
Feature request: Enable deployment to separate linux host/managed host

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-deploy#11]
Currently OpenConext-deploy is able to install OpenConext to the DTAP-environment of SURFconext and via vagrant to a local VM.

Please add the possibility to deploy OpenConext to a separate (user defined) linux host (managed host).
Prerequisites of the managed host are: 
- clean install with an OpenConext supported OS (e.g. CentOS 5.5)
- ssh enabled
- phyton 2.5+ installed (Ansible requirement)
  
If required running a few scripts before installation of OpenConext may be requested to run (change default passwords, specify managed host information: ip-address/username/etc)

**Comment by hanswesterbeek** [comment]
The CentOS version is 6.5. But yes, this request is duly noted.

**Comment by thijskh** [comment]
https://github.com/OpenConext/OpenConext-deploy/wiki/Installation-steps-to-deploy-OpenConext-on-a-single-system-other-than-the-Vagrant-VM
