### ISSUE TITLE
Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by tomkuipers** [OpenConext/OpenConext-deploy#111]
The provision-vagrant script is showing errors when trying to connect to both created instances.

```
PLAY [all] *********************************************************************

TASK [Read vars from secrets file] *********************************************
ok: [localhost]
ok: [192.168.66.99]
ok: [192.168.66.98]

PLAY [loadbalancer:php-apps:java-apps:storage] *********************************

TASK [setup] *******************************************************************
ok: [192.168.66.99]
fatal: [192.168.66.98]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

TASK [common : set timezone] ***************************************************
fatal: [192.168.66.99]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    to retry, use: --limit @/Users/tomk/Documents/Vagrant/OpenConext/OpenConext-deploy-217.1/provision-vm.retry

PLAY RECAP *********************************************************************
192.168.66.98              : ok=1    changed=0    unreachable=1    failed=0   
192.168.66.99              : ok=2    changed=0    unreachable=1    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

No website is running at https://welcome.vm.openconext.org/

**Comment by quartje** [comment]
It seems we use a non default virtualbox network. What happens when you run this command before trying again?
`vboxmanage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1`

**Comment by tomkuipers** [comment]
@quartje Still the same result as before.

```
PLAY [all] *********************************************************************

TASK [Read vars from secrets file] *********************************************
ok: [localhost]
ok: [192.168.66.99]
ok: [192.168.66.98]

PLAY [loadbalancer:php-apps:java-apps:storage] *********************************

TASK [setup] *******************************************************************
fatal: [192.168.66.98]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [192.168.66.99]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
	to retry, use: --limit @/Users/tomk/Documents/Vagrant/OpenConext/OpenConext-deploy-217.1/provision-vm.retry

PLAY RECAP *********************************************************************
192.168.66.98              : ok=1    changed=0    unreachable=1    failed=0   
192.168.66.99              : ok=1    changed=0    unreachable=1    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0  

```

I have multiple other VM's configured in my VirtualBox. would this mean 'vboxnet0' does not apply?

**Comment by quartje** [comment]
The problem seems to be that the virtualbox hosts are not accessible from your deployment host. Can you ping the two virtual machines? If not, can you check if two machines have a network card (adpater 2) attached to "host-only adapter".  If so, does it have the network 192.168.66.0/24 configured (under preferences/network/Host-only networks/) configured on the network that is attached to the host-only adapter?

**Comment by tomkuipers** [comment]
You're right, both hosts cannot be pinged:
```
$ ping 192.168.66.98
PING 192.168.66.98 (192.168.66.98): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
ping: sendto: No route to host
Request timeout for icmp_seq 4
^C
--- 192.168.66.98 ping statistics ---
6 packets transmitted, 0 packets received, 100.0% packet loss

$ ping 192.168.66.99 
PING 192.168.66.99 (192.168.66.99): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- 192.168.66.99 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
```

<img width="772" alt="vbox_network_hostonly" src="https://cloud.githubusercontent.com/assets/701208/19189474/7523c670-8c98-11e6-87c7-2600ecb36210.png">

Found something, the 'advanced' option showed 'promiscuous mode' set to 'deny'. Changing it to 'allow-all' made the host accessible.

<img width="658" alt="vbox_network_promiscuous" src="https://cloud.githubusercontent.com/assets/701208/19189858/799071f2-8c9a-11e6-92b0-235610ecd7d9.png">

Modified Vagrantfile to set promiscuous mode by adding 'vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]' twice.

$ vagrant ssh lb_centos7
> reboot
$ ping 192.168.66.98
Success!

$ vagrant ssh apps_centos7
> reboot
$ ping 192.168.66.99
Success!

After successfull ping run ./provision-vagrant again, now it will succeed.

**Comment by quartje** [comment]
The first error seems to be a Ansible bug which only occurs on MacOSX. See https://github.com/ansible/ansible-modules-core/issues/4390. GNU tar is needed for this to work. We'll fix this by using a zip file in stead of a tar.gz file. 
The second issue is a bit unexpected. If you run the playbook a second time, does the error occur again?

**Comment by tomkuipers** [comment]
Running ./provision-vagrant again still fails at the same task:

```
TASK [aa : wait for aa to start] ***********************************************
fatal: [192.168.66.99]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:9198"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [httpd : restart httpd] ****************************************
	to retry, use: --limit @/Users/tomk/Documents/Vagrant/OpenConext/OpenConext-deploy-217.1/provision-vm.retry

PLAY RECAP *********************************************************************
192.168.66.98              : ok=31   changed=3    unreachable=0    failed=0   
192.168.66.99              : ok=337  changed=7    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by quartje** [comment]
The service was not started correctly. As this is a very new service, it was not added to our tests yet.
This problem has been fixed in commit 32153cb80cfc2c30c8a80a289203bb9f1f14b8d3

**Comment by tomkuipers** [comment]
Well there is some progress, but still some aa task is failing:

```
TASK [aa : Copy systemd service file] ******************************************
fatal: [192.168.66.99]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/tomk/Documents/Vagrant/OpenConext/OpenConext-deploy-217.1/templates/spring-boot.service.j2'"}
```

This templates directory contains 'spring-boot.j2' but not 'spring-boot.service.j2'.
Will this run on OSX as systemd is Linux specific isn't it?

**Comment by quartje** [comment]
systemd is indeed Linux specific, but it is used on the target host, not on your deployment host. 
The file should be there, see: https://github.com/OpenConext/OpenConext-deploy/blob/master/templates/spring-boot.service.j2
Are you sure you have the latest version of OpenConext-deploy checked out?

**Comment by tomkuipers** [comment]
> Are you sure you have the latest version of OpenConext-deploy checked out?

I checked out the latest release version, https://github.com/OpenConext/OpenConext-deploy/releases/tag/217.1, because I thought a release is more stable then master.
I'll try master now.

**Comment by tomkuipers** [comment]
Yes, all fine now. Just a warning a the end, but no failures.

```
PLAY RECAP *********************************************************************
192.168.66.98              : ok=33   changed=3    unreachable=0    failed=0   
192.168.66.99              : ok=424  changed=164  unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin (</Users/tomk/Documents/Vagrant/OpenConext/OpenConext-deploy-
master/callback_plugins/profile_tasks.CallbackModule object at 0x10fd08290>): 'tuple' object has no attribute 'elapsed'

```

**Comment by quartje** [comment]
Excellent! I will close this issue then, please feel free to open another issue might any question arise.
