### ISSUE TITLE
ADFS v3.0 as an IdP <samlp:Scoping>  issue

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#115]
Hi guys,

I noticed that Thijs had created this issue with SimpleSAMLphp just about a month ago here:
https://github.com/simplesamlphp/simplesamlphp/issues/498

Have you guys figured out any sort of workaround to get this working with OpenConext?  We're trying to onboard a couple of entities that use ADFS, but we're running into the same problem.

Thanks!

**Comment by thijskh** [comment]
This works already in OprnConext Engine. Just set 'coin:disable_scoping' in Serviceregistry for that IDP
