### ISSUE TITLE
Provide instructions to create a control host for ansible other then localhost

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-deploy#12]
Please provide information to install ansible and deploy openconext from an other machine then localhost.
The current instructions are for localhost to be the control host.

Example:
````
    yum install git
    yum install gpg
    yum install ansible
    useradd openconext
    su - openconext
    git clone https://github.com/OpenConext/OpenConext-deploy.git
````

**Comment by thijskh** [comment]
https://github.com/OpenConext/OpenConext-deploy/wiki/Installation-steps-to-deploy-OpenConext-on-a-single-system-other-than-the-Vagrant-VM
