### ISSUE TITLE
Remove/Rename file roles/mujina-idp/tasks/provision_grouper.yml

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-deploy#13]
In the mujina-idp there is a tasks file for the provisioning of grouper.

Please remove or rename the file roles/mujina-idp/tasks/provision_grouper.yml

**Comment by thijskh** [comment]
The task exists to add the mujina admin user to grouper.

Maybe it suffices to move this to the grouper role and always provision this admin user on an initial install?

**Comment by thijskh** [comment]
Removed in 593421b79658229787f7095b82dd98ba7fc5a841
