### ISSUE TITLE
Unable to build release of EngineBlock on development environment

### ISSUE THREAD

**Issue by DRvanR** [OpenConext/OpenConext-deploy#133]
In order to be able to build a release for [OpenConext/OpenConext-engineblock][eb-github] the [`bin/makeRelease.sh`][makerelease] script is used. In order to successfully use this script, the following packages should be installed on the development environment:

- php-gmp
- git

These are currently not installed and thus no release can be generated.

[eb-github]: https://github.com/OpenConext/OpenConext-engineblock
[makerelease]: https://github.com/OpenConext/OpenConext-engineblock/blob/master/bin/makeRelease.sh

**Comment by DRvanR** [comment]
The referenced PR on OpenConext-engineblock removes the need for php-gmp

**Comment by quartje** [comment]
fixed in 03ec1a5d27848499e2018b2ee942e53c7f1457e5
