### ISSUE TITLE
Teams appending nl:surfnet:diensten  to names

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#134]
We got Teams working (thank you guys for decoupling grouper/ldap from it), and noticed it's appending a surfnet name string to all group names. 

In the [application.properties](
https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/teams/templates/application.properties.j2#L41) file, it looks like `defaultStemName` is set to `nl:surfnet:diensten`, which is being appended to the group name like so: `urn:collab:group:my.federation.com:nl:surfnet:diensten`

The `my.federation.com` is settable in the application.propeties.j2 template, while the `defaultStemName` is not. 

Should it be as simple as adding it as another configuration variable, or is there more to it than that?   If it's the fomer, I can just create a pull request for you guys.

Thanks

**Comment by thijskh** [comment]
It might be better to wait just a tiny bit until teams-ng is completed. @oharsta is this fixed in the new version?

**Comment by oharsta** [comment]
It is as simple as adding the defaultStemName to the application.properties.j2 and make it configurable per environment. I would recommend a default value of `nl:surfnet:diensten` in the main.yml in teams/defaults as otherwise we would need to change all the existing environment properties.

**Comment by thijskh** [comment]
Fine!

**Comment by precurse** [comment]
Looking forward to seeing what teams-ng looks like.  Is there a list of improvements/features that it'll bring along with it?

Thanks!

**Comment by oharsta** [comment]
https://www.pivotaltracker.com/n/projects/1443920
