### ISSUE TITLE
Adding new https certificates to you already installed OC box

### ISSUE THREAD

**Issue by mkoyan44** [OpenConext/OpenConext-deploy#136]
Dear All,

Can you please help me to install my * certificate in existing deployment or from scratch.
I follow this steps to install.
1- I created a file in certs directory named star.prod.pem with content my 'start' certificate and intermediate CA certificates from my provider.
2 - https_key from secrets file
3 -  ansible-playbook -v -i "environments/prod/inventory" -u "root" -K provision-prod.yml  --extra-vars="secrets_file=environments/prod/secrets/prod.yml" --tags lb   

The issue is that HaProxy doesn't accept star_haproxy.pem file but when manually add cert and privet key in star_haproxy.pem it still run with untrusted mode.

Please help.
Looking forward to your fast response.
Thanks.

**Comment by quartje** [comment]
I'm afraid there is a mistake in the documentation. Your certificate should be saved as star.<domain>.pem, where <domain> is the domain you used to set up this environment.

**Comment by mkoyan44** [comment]
Thanks that works.
But I am still running in untrusted mode.I wonder if the issue caused by using *.openconext.asnet.am subdomain when my certificate ordered for *.asnet.am.
Can it cause a problem?

**Comment by thijskh** [comment]
Yes: in browsers a `*` in a certifiate is only valid for one dns hostname label. So `*.b.a` will match `c.b.a` but not `d.c.b.a`.

**Comment by mkoyan44** [comment]
ok,Thanks a lot
