### ISSUE TITLE
 An error occurred page.

### ISSUE THREAD

**Issue by mkoyan44** [OpenConext/OpenConext-deploy#137]
Dear All,

After fresh installation when  I try to open services such as ServiceRegistery or EngineBlock we only see the An error occurred page, but at the same time when we open same pages with Vagrant, everything went ok.Please help me identify possible mistakes and errors.

Inaccessible URLs : 
https://engine.openconext.asnet.am/authentication/idp/metadata
https://engine.openconext.asnet.am/
etc ...

**Comment by quartje** [comment]
Engineblock will create a Unique Request ID. You can grep /var/log/messages for this Request ID to get the full error message

**Comment by mkoyan44** [comment]
Please see my messages file:

May 29 15:08:44 openconext Apache-Playground: 127.0.0.1 - - [29/May/2017:15:08:44 +0200] "GET /health HTTP/1.0" 200 103 "-" "-" "127.0.0.1"
May 29 15:08:45 openconext Apache-VOOT: 127.0.0.1 - - [29/May/2017:15:08:45 +0200] "GET /health HTTP/1.0" 200 15 "-" "-" "127.0.0.1"
May 29 15:08:47 openconext.asnet.am haproxy[9986]: 93.187.165.47:40606 [29/May/2017:15:08:46.981] ssl_ip/1: SSL handshake failure
May 29 15:08:47 openconext.asnet.am PDPMAIN: [pool-4302-thread-1] pdp.serviceregistry.UrlResourceServiceRegistry Error in refreshing / initializing metadata
May 29 15:08:47 openconext.asnet.am #011java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching multidata.openconext.asnet.am found.
May 29 15:08:47 openconext.asnet.am #011at pdp.serviceregistry.BasicAuthenticationUrlResource.isModified(BasicAuthenticationUrlResource.java:54)
May 29 15:08:47 openconext.asnet.am #011at pdp.serviceregistry.UrlResourceServiceRegistry.doInitializeMetadata(UrlResourceServiceRegistry.java:81)
May 29 15:08:47 openconext.asnet.am #011at pdp.serviceregistry.UrlResourceServiceRegistry.initializeMetadata(UrlResourceServiceRegistry.java:107)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
May 29 15:08:47 openconext.asnet.am #011at java.lang.Thread.run(Thread.java:748)
May 29 15:08:47 openconext.asnet.am #011Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching multidata.openconext.asnet.am found.
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
May 29 15:08:47 openconext.asnet.am #011at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
May 29 15:08:47 openconext.asnet.am #011at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
May 29 15:08:47 openconext.asnet.am #011at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
May 29 15:08:47 openconext.asnet.am #011at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
May 29 15:08:47 openconext.asnet.am #011at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
May 29 15:08:47 openconext.asnet.am #011at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
May 29 15:08:47 openconext.asnet.am #011at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
May 29 15:08:47 openconext.asnet.am #011at pdp.serviceregistry.BasicAuthenticationUrlResource.isModified(BasicAuthenticationUrlResource.java:50)
May 29 15:08:47 openconext.asnet.am #011at pdp.serviceregistry.UrlResourceServiceRegistry.doInitializeMetadata(UrlResourceServiceRegistry.java:81)
May 29 15:08:47 openconext.asnet.am #011at pdp.serviceregistry.UrlResourceServiceRegistry.initializeMetadata(UrlResourceServiceRegistry.java:107)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
May 29 15:08:47 openconext.asnet.am #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
May 29 15:08:47 openconext.asnet.am #011at java.lang.Thread.run(Thread.java:748)

**Comment by quartje** [comment]
This only shows part of it, the engineblock error is not in it. But I think your main issue is the wrong certificate SAN. Engineblock needs to contact serviceregistry.yourdomain over https. This fails because of the certificate error I presume

**Comment by mkoyan44** [comment]
Yes, I see.

This occurs after fresh installation, so in order to resolve issue I need to change engine block certificate and key /etc/openconext/engineblock.{crt,key} file, right?

**Comment by mkoyan44** [comment]
Dear All,

Please see my log file for more clear view.

[messages.txt](https://github.com/OpenConext/OpenConext-deploy/files/1037684/messages.txt)

**Comment by quartje** [comment]
This shows up in the errors:
engineblock.ALERT: Unable to contact JANUS and no stale cache found for possible reuse! 

That means that Engineblock is unable to reach Serviceregistry. There are two usual causes for this:
1) The hostname serviceregistry.\<yourdomain\> is  not resolvable. Either add it to the DNS or to your /etc/hosts file on the target machine
2) The target machine does not accept the certificate used for serviceregistry. You can test this by issuing a "curl https://serviceregistry.\<yourdomain\>" on the target host. If a certificate warning shows up you should fix that.
