### ISSUE TITLE
Development provisioning hangs on teams

### ISSUE THREAD

**Issue by MKodde** [OpenConext/OpenConext-deploy#140]
**Problem**
When provisioning the development environment on revision: [0af087e](https://github.com/OpenConext/OpenConext-deploy/commit/0af087e42a14be4111f8eb53a77af0b836897f6e) (and several commits 'downwards') the playbook hangs on the `start the teams service` task.

The timeout period of 30 seconds is reached and provisioning stops. Elongating the timeout period did not provide a workaround for this issue.

**Steps to reproduce**
1. Start by setting up your development environment prerequisite described in: this [development.md](https://github.com/OpenConext/OpenConext-deploy/blob/master/DEVELOPMENT.md)
2. In the `Openconnext-deploy` directory:
    1. `vagrant destroy`
    2. `rm -rf .vagrant`
    3. `ENV=dev vagrant up`

**Comment by thijskh** [comment]
Is a known issue worked on right now. Quick fix is to comment out the teams role.

**Comment by thijskh** [comment]
Should be fixed now.

**Comment by MKodde** [comment]
Thanks I'll try to validate this as soon as possible.
