### ISSUE TITLE
engine is reading stale files after symlink update

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-deploy#143]
After deploying a new version of engine I see errors like the one below:
`engineblock.ERROR: file_get_contents(/opt/openconext/OpenConext-engineblock-5.4.0/application/configs/attributes-v2.2.0.json): failed to open stream: No such file or directory [/opt/openconext/OpenConext-engineblock-master/library/EngineBlock/Application/DiContainer.php:241] `…

When updating the `/opt/openconext/OpenConext-engineblock` symlink is changed and old versions are removed. The error indicates that updating the symlink does not immediately switch to the new engineblock.

After restarting httpd & php-fpm the errors disappear.

**Comment by thijskh** [comment]
There is already a `notify: restart httpd` in the engine role. Any idea why that was/is not triggered in your case?

**Comment by thijskh** [comment]
I cannot reproduce this, when setting `engine_version: "master"` in group vars, the branch is installed and at the end httpd is restarted.

**Comment by thijskh** [comment]
Could this have been related to a half-successful / partially failed ansible deploy?

**Comment by thijskh** [comment]
I'm not seeing this after several deploys. I suspect there's something in play here with a failed ansible run.
