### ISSUE TITLE
Exception: Provider pdp.xacml.CustomFunctionDefinitionFactory not found 

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#150]
I started receiving these exception emails recently when using the v234/v235.1 OpenConext-deploy releases:
```
Exception reading xacml.properties
--
org.apache.openaz.xacml.util.FactoryException: Provider pdp.xacml.CustomFunctionDefinitionFactory not found
```
It looks like that this `CustomFunctionDefinitionFactory` was added to the `xacml.conext.properties.j2` file about 2 months ago: https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/pdp/templates/xacml.conext.properties.j2#L16 , but the latest PDP 1.2.12 release was tagged on July 6th -- This factory wasn't added until August.

So it looks like the -Deploy is adding the Factory to the properties file, but the PDP version isn't yet compiled with it.  I think that explains why we're getting that exception.

Is it safe to ignore these emails for the time being until the next PDP release?

Thanks

**Comment by thijskh** [comment]
@oharsta

**Comment by oharsta** [comment]
There is a new release 1.2.14 which has been deployed and tagged. The OpenConext-deploy project - tag 236 - is updated to use the latest version of PDP. @precurse your analysis was right.
