### ISSUE TITLE
ansible deprecration warning

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-deploy#151]
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.

[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by thijskh** [comment]
I don't get this with Ansible 2.5. Is it still relevant, if so when do you get those?

**Comment by quartje** [comment]
Deprecations have been removed. Closing this issue, if any other deprecations arise please open another issue
