### ISSUE TITLE
Monitoring-tests OIDC credentials

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#176]
Hello,

I have the monitoring-tests working, but the only part of it that's not working is obtaining the OIDC token so it can test VOOT.

Looking at the monitoring-tests application configuration, it seems that `voot: authz` section is using a client ID specific for monitoring-tests, while the `voot: oidc` section is re-using the client ID for authzplayground (`authzplayground.springapp_oidc_client_id`): 

https://github.com/OpenConext/OpenConext-deploy/blob/7909477ca5b945d0b1de370cfddab8ac2bcf40af/roles/monitoring-tests/templates/application.yml.j2#L27-L39

In order for monitoring-tests to successfully obtain a token, the "client credentials" grant type needs to be enabled, but that's not set in the authz-playground client:  https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/oidc/templates/clientsAndResources.yml.j2#L10-L13

Would monitoring-tests having its own client ID in OIDC be the right way of handling this? Or does it need to use the authz-playground one?

Thanks,
Andrew

**Comment by quartje** [comment]
Hi Andrew,

Indeed, it is better to use the a seperate client with only client credentials grant type. I'll configure this for OpenConext-deploy

**Comment by quartje** [comment]
This commit: https://github.com/OpenConext/OpenConext-deploy/commit/6f6030cc27131061a886bddd63d661dd96fbc3e4 should fix the issue. It also allows for a more flexible list of clients and resources. Take the oidcadmin: from roles/oidc/defaults/main.yml and adapt it to your needs to add or remove clients and resource servers and put it in your group_vars. 
The default contains everything you need to get the OpenConext stack running

**Comment by precurse** [comment]
No problem. Thanks for the quick fix!

Cheers
