### ISSUE TITLE
OperationFailure: Authentication failed

### ISSUE THREAD

**Issue by bcarroll** [OpenConext/OpenConext-deploy#220]
TASK [mongo : Create mongo database users] **********************************************************************************************************
[DEPRECATION WARNING]: evaluating mongo_primary as a bare variable, this behaviour will go away and you might need to add |bool to the expression in
 the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationFailure: Authentication failed.
failed: [localhost] (item={u'db_name': u'metadata', u'password': u'jbOqItweroxyIFaMlQcp', u'name': u'managerw'}) => {"ansible_loop_var": "item", "changed": false, "item": {"db_name": "metadata", "name": "managerw", "password": "jbOqItweroxyIFaMlQcp"}, "msg": "unable to connect to database: Authentication failed."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationFailure: Authentication failed.
failed: [localhost] (item={u'db_name': u'oidcng', u'password': u'1LPXX690ZjiqSm0C57og', u'name': u'oidcngrw'}) => {"ansible_loop_var": "item", "changed": false, "item": {"db_name": "oidcng", "name": "oidcngrw", "password": "1LPXX690ZjiqSm0C57og"}, "msg": "unable to connect to database: Authentication failed."}

PLAY RECAP ******************************************************************************************************************************************
localhost                  : ok=70   changed=1    unreachable=0    failed=1    skipped=83   rescued=0    ignored=0

**Comment by quartje** [comment]
Hi Brett,

This problem typically happens when you have provisioned Mongo and overwrite your secrets file afterwards. For instance when you rerun the prep-env script again.

The solution is to either reset the admin password, or to uninstall mongo, and run the mongo role again. In case you chose the latter, you should delete the contents of /var/lib/mongo before you run the mongo again.
