### ISSUE TITLE
Playbook failure installing NFS client

### ISSUE THREAD

**Issue by judielaine** [OpenConext/OpenConext-deploy#232]
I'm not experienced with ansible and virtualbox. I recognize this is more to do with centos7 going onto the virtualBox than strictly with OpenConext, but advice is welcome.  I'm attempting this on macOS High Sierra 10.13.6 (17G7024). I upgraded and cleaned up my stale brew environment, reinstalled python (i'm using pip3 and not pip), and tried to follow the instructions in  README.md  as closely as possible.

> No extra roles found to be downloaded
> Bringing machine 'lb_centos7' up with 'virtualbox' provider...
> Bringing machine 'apps_centos7' up with 'virtualbox' provider...
> ==> lb_centos7: Box 'CentOS-7.0' could not be found. Attempting to find and install...
>     lb_centos7: Box Provider: virtualbox
>     lb_centos7: Box Version: >= 0
> ==> lb_centos7: Box file was not detected as metadata. Adding it directly...
> ==> lb_centos7: Adding box 'CentOS-7.0' (v0) for provider: virtualbox
>     lb_centos7: Downloading: https://build.openconext.org/vagrant_boxes/virtualbox-centos7.box
>     lb_centos7: Progress: 5% (Rate: 1782k/s, Estimated time remaining: 0:05:29)
> 
>    lb_centos7: Downloading: https://build.openconext.org/vagrant_boxes/virtualbox-centos7.box
> ==> lb_centos7: Successfully added box 'CentOS-7.0' (v0) for 'virtualbox'!
> ==> lb_centos7: Importing base box 'CentOS-7.0'...
> ==> lb_centos7: Matching MAC address for NAT networking...
> ==> lb_centos7: Setting the name of the VM: OpenConext Engineblock Loadbalancer
> ==> lb_centos7: Clearing any previously set network interfaces...
> ==> lb_centos7: Preparing network interfaces based on configuration...
>     lb_centos7: Adapter 1: nat
>     lb_centos7: Adapter 2: hostonly
> ==> lb_centos7: Forwarding ports...
>     lb_centos7: 22 (guest) => 2222 (host) (adapter 1)
> ==> lb_centos7: Running 'pre-boot' VM customizations...
> ==> lb_centos7: Booting VM...
> ==> lb_centos7: Waiting for machine to boot. This may take a few minutes...
>     lb_centos7: SSH address: 127.0.0.1:2222
>     lb_centos7: SSH username: vagrant
>     lb_centos7: SSH auth method: private key
>     lb_centos7: Warning: Connection reset. Retrying...
>     lb_centos7: Warning: Remote connection disconnect. Retrying...
>     lb_centos7:
>     lb_centos7: Vagrant insecure key detected. Vagrant will automatically replace
>     lb_centos7: this with a newly generated keypair for better security.
>     lb_centos7:
>     lb_centos7: Inserting generated public key within guest...
>     lb_centos7: Removing insecure key from the guest if it's present...
>     lb_centos7: Key inserted! Disconnecting and reconnecting using new SSH key...
> ==> lb_centos7: Machine booted and ready!
> ==> lb_centos7: Checking for guest additions in VM...
>     lb_centos7: The guest additions on this VM do not match the installed version of
>     lb_centos7: VirtualBox! In most cases this is fine, but in rare cases it can
>     lb_centos7: prevent things such as shared folders from working properly. If you see
>     lb_centos7: shared folder errors, please make sure the guest additions within the
>     lb_centos7: virtual machine match the version of VirtualBox you have installed on
>     lb_centos7: your host and reload your VM.
>     lb_centos7:
>     lb_centos7: Guest Additions Version: 5.1.26
>     lb_centos7: VirtualBox Version: 6.0
> ==> lb_centos7: Setting hostname...
> ==> lb_centos7: Configuring and enabling network interfaces...
> ==> lb_centos7: Installing NFS client...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> if command -v dnf; then
>   if `dnf info -q libnfs-utils > /dev/null 2>&1` ; then
>     dnf -y install nfs-utils libnfs-utils portmap
>   else
>     dnf -y install nfs-utils nfs-utils-lib portmap
>   fi
> else
>   yum -y install nfs-utils nfs-utils-lib portmap
> fi
> 
> if test $(ps -o comm= 1) == 'systemd'; then
>   /bin/systemctl restart rpcbind nfs
> else
>   /etc/init.d/rpcbind restart
>   /etc/init.d/nfs restart
> fi
> 
> 
> Stdout from the command:
> 
> Loaded plugins: fastestmirror
> 
> 
> Stderr from the command:
> 
> 
> 
>  One of the configured repositories failed (Unknown),
>  and yum doesn't have enough cached data to continue. At this point the only
>  safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
>      1. Contact the upstream for the repository and get them to fix the problem.
> 
>      2. Reconfigure the baseurl/etc. for the repository, to point to a working
>         upstream. This is most often useful if you are using a newer
>         distribution release than is supported by the repository (and the
>         packages for the previous distribution release still work).
> 
>      3. Run the command with the repository temporarily disabled
>             yum --disablerepo=<repoid> ...
> 
>      4. Disable the repository permanently, so yum won't use it by default. Yum
>         will then just ignore the repository until you permanently enable it
>         again or use --enablerepo for temporary usage:
> 
>             yum-config-manager --disable <repoid>
>         or
>             subscription-manager repos --disable=<repoid>
> 
>      5. Configure the failing repository to be skipped, if it is unavailable.
>         Note that yum will try to contact the repo. when it runs most commands,
>         so will have to try and fail each time (and thus. yum will be be much
>         slower). If it is a very temporary problem though, this is often a nice
>         compromise:
> 
>             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
> 
> Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
> Failed to restart rpcbind.service: Unit not found.
> Failed to restart nfs.service: Unit not found.

**Comment by quartje** [comment]
The last few lines suggest that yum is not able to update its metadata, so my guess is that the VM does not have network connectivity. The VM should have two networks configured: The first attached to "NAT", the second attached to Host-only adapter "vboxnet0"

**Comment by judielaine** [comment]
Would that be an upstream provider issue with ... vagrant?

**Comment by quartje** [comment]
The problem is with the VirtualBox VM.
Are you able to ssh to the vagrant machines? You can use the following commands:
```
vagrant ssh lb_centos7
or
vagrant ssh apps_centos7
```

Do the VMs have internet connectivity?

**Comment by judielaine** [comment]
I'm going to guess the upstream repository for one of the mentioned packages (nfs-utils libnfs-utils portmap) was off on Saturday and has since been kicked. ("One of the configured repositories failed (Unknown),and yum doesn't have enough cached data to continue. At this point the only safe thing yum can do is fail. ") I ran ./provision today (because the machine i ran it on had been off) and the full provisioning completed. 

Thanks for the comments!
