### ISSUE TITLE
Improve Travis tests by adding a build of the development VM to the tests

### ISSUE THREAD

**Issue by MKodde** [OpenConext/OpenConext-deploy#249]
Would it be possible to include the development specific roles to the existing OpenConext deploy tests? We often experience issues during the provisioning of our dev vm while the build for that revision is green on Travis.

**Comment by dj-wasabi** [comment]
Is Molecule something that could help with this? With Molecule you are easily able to spin up 1 or more Docker containrs and execute Ansible to it, run (idempotency|testinfra) tests to verify correct installation. See: https://molecule.readthedocs.io/en/latest/
