### ISSUE TITLE
API role has been removed, but other files weren't updated

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-deploy#27]
It seems the role for Openconext-Api has eben removed (as it has been replaced by -voot), but references to api haven't been cleaned from group_vars and secrets

**Comment by thijskh** [comment]
This can in principle be removed already, but I'll do this when api is actually gone from the production platform.

**Comment by thijskh** [comment]
Fixed in dc52a086c20b4e31b00d4520949fa3a3041e3a87
