### ISSUE TITLE
How can the risk of feature toggle technical debt be reduced?

### ISSUE THREAD

**Issue by rmahdav** [OpenConext/OpenConext-deploy#278]
Dear developers,

I, Rezvan Mahdavi Hezaveh (rmahdav@ncsu.edu), and my colleague, Nirav Ajmeri (najmeri@ncsu.edu), software engineering researchers from North Carolina State University are conducting an academic study of feature toggles and technical debt.
   
In our investigations on GitHub repositories, we noticed that you are using feature toggles in your repository. For instance, in this [commit](https://github.com/OpenConext/OpenConext-deploy/commit/77c34fc4d6dbec8b34bebbb7019e60c27e8981b6) and in this [commit](https://github.com/OpenConext/OpenConext-deploy/commit/8945485795683e93e81bcebfcb6d9e2c60bc0ef2) two new feature toggles are added. Based on the name of the toggles and their values, it seems they are same toggles with same purpose. Was not one of them enough?

We would appreciate your collaboration in this study by answering an anonymous survey based upon your experience with the feature toggles. This survey has 20 questions and the estimated time to answer these questions is 10 minutes. 

The link to the survey is here: https://ncsu.qualtrics.com/jfe/form/SV_5BGE3wNDUtFQqMd

Once you start answering the survey questionnaire, you will have 24 hours to finish it.
As an appreciation for your time, we will conduct a random drawing and give $25 Amazon gift cards to five selected survey respondents. Also, we will share our results with you.

Thanks

**Comment by thijskh** [comment]
Thanks, see my answer in OpenConext/OpenConext-manage#35
