### ISSUE TITLE
Authz-server started check may fail deployment

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-deploy#28]
Last task of roles/authz-server/tasks/main.yml may fail if authzserver is not yet started. Timing issue?

https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/authz-server/tasks/main.yml#L36
----
- name: ensure the service is started
  service: name=authz-server enabled=yes state=started
----

Task is successful during rerun.

**Comment by remold** [comment]
Workaround used for teams is:

```
# no idea why this is necessary, as the init script returns an ok status also
# if teams is still initializing.  Waiting for the port to open works well
# though, and seems like to correct way to handle this.
- name: start the teams service
  service: name=teams state=started enabled=yes
  ignore_errors: true

- name: wait for teams to start
  wait_for: connect_timeout=30 port={{ springapp_tcpport }} state=started

- name: ensure the service is started
  service: name=teams enabled=yes state=started
```

There may be other services which have the same problem (most likely the tomcat/java services).

**Comment by quartje** [comment]
The restart of this element has a timeout of 45 seconds now which resolves this issue.
