### ISSUE TITLE
roles/vm_only_provision_eb_sr/templates/serviceregistry.sql.j2 contains hardcoded passwords and domain

### ISSUE THREAD

**Issue by remold** [OpenConext/OpenConext-deploy#30]
The file roles/vm_only_provision_eb_sr/templates/serviceregistry.sql.j2 contains hardcoded passwords and domain. This is not an issue for installing a default VM, but not for any other deployment.

Please update domain to {{ base_domain }}
and take passwords from the secrets-file.

**Comment by thijskh** [comment]
Fixed in #30
