### ISSUE TITLE
Installations problem

### ISSUE THREAD

**Issue by sergioloyola** [OpenConext/OpenConext-deploy#300]
Good morning, I'm installing openConext, following the tutorial "Installation steps to deploy OpenConext on a single system other than the Vagrant VM centOS7". But it is giving me the following error:

TASK [authz-admin: Copy config for default clients and resource servers] ********************************************
fatal: [10.22.0.184]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute oidc_checkToken_secret'"}

My local workstation has LinuxMint 20 installed and Centos 7 server installed

**Comment by quartje** [comment]
Hi, 

Unfortunately, master was broken. The fix was already planned in a PR, which I've just merged. This should fix your issue!
