### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by sergioloyola** [OpenConext/OpenConext-deploy#306]
good afternoon, I'm following the following tutorial https://github.com/OpenConext/OpenConext-deploy/wiki/Installation-steps-to-deploy-OpenConext-on-a-single-system-other-than-the-Vagrant- VM-centOS7 and I get the following error:

**fatal: [10.22.0.184]: FAILED! => {"changed": true, "cmd": ["php72", "app/console", "doctrine:migrations:migrate", "-n", "--env=prod"], "delta": "0:00:00.113817", "end": "2020-11-16 20:46:10.850287", "msg": "non-zero return code", "rc": 1, "start": "2020-11-16 20:46:10.736470", "stderr": "\nIn AbstractMySQLDriver.php line 93:\n                                                                               \n  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  \n  ser 'ebrw'@'localhost' (using password: YES)                                 \n                                                                               \n\nIn PDOConnection.php line 31:\n                                                                               \n  SQLSTATE[HY000] [1045] Access denied for user 'ebrw'@'localhost' (using pas  \n  sword: YES)                                                                  \n                                                                               \n\nIn PDOConnection.php line 27:\n                                                                               \n  SQLSTATE[HY000] [1045] Access denied for user 'ebrw'@'localhost' (using pas  \n  sword: YES)                                                                  \n                                                                               \n\ndoctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 93:", "                                                                               ", "  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  ", "  ser 'ebrw'@'localhost' (using password: YES)                                 ", "                                                                               ", "", "In PDOConnection.php line 31:", "                                                                               ", "  SQLSTATE[HY000] [1045] Access denied for user 'ebrw'@'localhost' (using pas  ", "  sword: YES)                                                                  ", "                                                                               ", "", "In PDOConnection.php line 27:", "                                                                               ", "  SQLSTATE[HY000] [1045] Access denied for user 'ebrw'@'localhost' (using pas  ", "  sword: YES)                                                                  ", "                                                                               ", "", "doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]"], "stdout": "                                                                         \n                    OpenConext EngineBlock Migrations                    \n                                                                         ", "stdout_lines": ["                                                                         ", "                    OpenConext EngineBlock Migrations                    ", "                                                                         "]}

NO MORE HOSTS LEFT ******************************************************************************************************************************************************

PLAY RECAP **************************************************************************************************************************************************************
10.22.0.184                : ok=125  changed=0    unreachable=0    failed=1    skipped=103  rescued=0    ignored=0**

**Comment by quartje** [comment]
Did you try to restart your installation by doing a second "prep-env" after you ran the installation before?

If you did, the root password of mysql changed, rendering the mysql effectively inaccessable. Removing mysql completely (including /var/lib/mysql) and restarting the ansible playbook run should fix your issue

**Comment by quartje** [comment]
I'm closing this issue. If you have any additional considerations, please don't hesitate to open another issue.
