### ISSUE TITLE
PDP install breaks

### ISSUE THREAD

**Issue by relaxnow** [OpenConext/OpenConext-deploy#44]
TASK [pdp : download snapshot of html archive] *********************************
fatal: [192.168.66.79]: FAILED! => {"changed": false, "dest": "/var/www/pdp/pdp-gui-1.0.2-20151222.102014-26.tar.gz", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://build.surfconext.nl/repository/public/snapshots/org/openconext//pdp-gui/1.0.2-SNAPSHOT/pdp-gui-1.0.2-20151222.102014-26.tar.gz"}

**Comment by quartje** [comment]
Fixed in https://github.com/OpenConext/OpenConext-deploy/commit/b8d1a875924c87cea15f7ae29c512c34f4c5aa7f
