### ISSUE TITLE
Do not run the docker container restart handler when the container task restarts the container

### ISSUE THREAD

**Issue by quartje** [OpenConext/OpenConext-deploy#454]
A Java container is restarted when one of the configuration files changes. This sometimes interferes with a container restart which is executed automatically when a new container is pulled in the container task. That sometimes leads to restarting a container when it is still doing migrations. Ideally it should only be restarted once every play. Or the container task never restarts, but sends a notify

**Comment by phavekes** [comment]
I've atempted to fix this in https://github.com/OpenConext/OpenConext-deploy/pull/455. Could you test this?
