### ISSUE TITLE
Ansible error when provisioning

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#50]
Hello,

I'm trying to re-provision the Vagrant VMs again, but noticing this error is popping up with the latest git clone:
```
TASK [aa : download html archive] **********************************************
fatal: [192.168.66.79]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download artifact org.openconext:aa-gui:tar.gz:1.0.1 because of HTTP Error 404: Not Foundfor URL https://build.surfconext.nl/repository/public/releases/org/openconext/aa-gui/1.0.1/aa-gui-1.0.1.tar.gz"}
```
Looking at https://build.surfconext.nl/repository/public/releases/org/openconext/  there's no longer an aa-gui folder..  Did it get removed by accident maybe?

Thanks!

**Comment by quartje** [comment]
This problem is fixed now. You should be able to provision the vm without any problems now. 
We will start this week with releases of OpenConext-deploy in which all elements are working and stable to prevent the problems you are experiencing now.
