### ISSUE TITLE
Other install doesn't mention required (Cent)OS

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-deploy#57]
https://github.com/OpenConext/OpenConext-deploy/wiki/Installation-steps-to-deploy-OpenConext-on-a-single-system-other-than-the-Vagrant-VM
Does not mention that CentOS is required and doesn't mention minimal (max?) version for succesful deploy.

**Comment by quartje** [comment]
I have added it to the introduction on the wiki.
