### ISSUE TITLE
Component roles should register SPs and IdPs in Manage

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-deploy#66]
Currently, a "fresh" Janus database is initialized in the vm_only_provision_eb_sr roleby overwriting the Janus DB with a random database dump.  This causes all kinds of problems, and makes it dangerous to run a VM deploy on a VM containing actual data.

The _nice_ way to solve this, would be using the Janus REST API to let each of the SPs and IdPs register in each respective role.  I.e., when Mujina IdP is installed, as part of the tasks in the mujina-idp role, it would check in the Janus REST API (by entityid) if it is already known in Janus, and if not, register itself.

**Comment by baszoetekouw** [comment]
Note that fixing this would also fix #29

**Comment by thijskh** [comment]
Janus is now Manage, but basic idea still holds.

**Comment by quartje** [comment]
This has been fixed now, all roles can now provision themselves in Manage, using one central role to do so. Closing this 4,5 year outstanding issue
