### ISSUE TITLE
please handle initialization of EB databases in the engineblock role

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-deploy#69]
Currently, the Engineblock database is provisioned in the `vm_only_provision_eb_sr` task by overwriting the EB database with a random database dump.  This causes all kinds of problems for OpenConext installs.  

Please integrate database initialization for EB in the engineblock role, for example by checking of the databse already exists, and if not, creating it with sane default values.

See https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/vm_only_provision_eb_sr/templates/engineblock.sql.j2 for the dump that is currently installed to provision the db.

**Comment by DRvanR** [comment]
As an FYI, it is on the roadmap of EB5 to replace the current database creation and migration tool. The plan is to have the new tool create an empty database through migrations. The tool also allows for the insertion of database fixtures. Those could be used for for instance provisioning of a dev env (using `when: develop`), but not when privisioning any other env. This to ensure that any current data is kept when provisioning any env, but when provisioning a new dev env it will contain sensible default data.

**Comment by baszoetekouw** [comment]
Sounds great!  
Would it be possible for the implementation to distinguish between the situation in which no database exists and the scheme needs to be created without any data (typical for deploying a new OpenConext environment), and the situation in which a sane default database (including content) needs to be provisioned (typical for a dev vm install)?

**Comment by DRvanR** [comment]
Yes that would be possible, albeit perhaps indirect. The insertion of the data is a separate step from the creation of the schema. The fist would be running the fixtures, the latter running the database migrations. The migrations should always run to ensure that the schema and app are compatible and are already configured as such. The fixtures should only run if the user opted in, to prevent (accidentally) overwriting data. 
Currently, there are already "development env only" steps in the provisioning ([example][1]), the loading of fixtures should only be done when running for develop. This ensures that running in a non-dev env the fixtures cannot be loaded. Furthermore the fixtures can be disabled for any non-dev or test (CI) env, but could be invoked manually as override should the fixtures still be wanted (e.g. deploying a new prod release on a test environment without data). But the exact implementation could better be discussed when actually implementing it :)

[1]: https://github.com/OpenConext/OpenConext-deploy/blob/b0742995f0ac25c068f181e550c3762e48cff54b/roles/engineblock5/tasks/main.yml#L17-L18

**Comment by quartje** [comment]
We've fixed the issue a bit differently: All entities needed by EB are now provisioned from within the roles. 
Since EB does not need itself to be present as an entity in it's own database anymore, no provisioning is needed from the EB point of view.  It's in the develop branch, we'll be merging this shortly. Closing this issue, which only took 4,5 years to fix :)
