### ISSUE TITLE
Fix ansible deployment of authZ-server and AuthZ-admin

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-deploy#70]
When deploying AuthZ and AuthZ-admin, the deploy breaks on ansible not being able to assertain of AuthZ-service and AuthZ-admin are started.
Typical error is: 

> TASK: [authz-server | ensure the service is started] **************************
> failed: [145.100.181.45] => {"failed": true}
> msg: [FAILED]

When I login to the deploy target however, _the service was started correctly_.

**Workaround**
Restarting the deploy ' fixes'  this problem as the scripts detect the service is already deployed and the deployment is skipped.

**Resolution**
Some testing has determined that the init scripts for authZ-server and AuthZ-admin are in fact returning the correct exit code, which suggests the templating is done correctly.
We could also not find a difference between deploymens using init.d or system.d

**Comment by baszoetekouw** [comment]
The template init script (https://github.com/OpenConext/OpenConext-deploy/blob/master/templates/spring-boot.j2) for spring boot apps is rather primitive, which is probably also causing this issue.  It should probably be adapted to use systemd or something like start-stop-daemon (or it's CentOS equivalent) instead of messing around with nohup.

**Comment by thijskh** [comment]
I believe that if you'd use a proper systemd unit you can return success as soon as the port is actually listening and not earlier.

**Comment by baszoetekouw** [comment]
Indeed.  That would be a much nicer implementation than my workaround here: https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/pdp/tasks/main.yml#l105-l113

**Comment by thijskh** [comment]
Replacing all init scripts with systemd units is definitely useful for proper process control, not only startup but also shutdown, handling crashes, process isolation and the like.

**Comment by quartje** [comment]
The replacement of the init scripts by systemd scripts is on the list to be implemented. It will be implemented before the CentOS7 upgrade takes place

**Comment by thijskh** [comment]
I think this has been addressed via a combination of the right checks, reduced startup times and maybe even unit scripts. I propose to close this issue, and address any concrete new occurrences that may happen in the future then.
