### ISSUE TITLE
Let's Encrypt Support

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#75]
Hey guys,

I wanted to see if you'd be interested in functionality with LetsEncrypt/Certbot to handle browser trusted HTTPS certificates.   We're looking at developing this for us, but if there's interest from your end we could look into integrating it with the main Openconext-deploy repo.

Andrew

**Comment by baszoetekouw** [comment]
Hi Andrew,
Sounds like a great idea!  Thought about adding Letsencrypt support before, it's never been high on our priority list, but please go ahead!  I think it wold be a great feature.

Bas

**Comment by baszoetekouw** [comment]
Btw, the main development is currently happening in the engineblock5-centos7 branch, so it would probably be best to add Letsencrypt there.  I expect this branch to replace master soonish.

**Comment by precurse** [comment]
We ended up switching to dns-01 verification using Openstack's DNS provider, which unfortunately won't really tie too well with the OpenConext-Deploy.  I'll close this issue for now.
