### ISSUE TITLE
Engineblock5 multi-environment question

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#83]
Hi guys.. I have a question regarding with how multiple environments are handled on the new version.  Since we have 3 environments (dev, demo, and prod), it's nice to be able to isolate each from one another.

One thing I've found with the `./prep-env` is that it creates a `files/php-template/certs` directory where only a single `engineblock.crt` file is copied to. However, this is outside of the `./environments/{ env }/`  directory.  If I have the development `.crt` file in that directory when I go to run the `production` playbook, the wrong cert will be used. 

I'm not sure if it's a bug, or if there was a specific reason for it being setup this way.  Any help would be great :)

Thanks again!

**Comment by precurse** [comment]
Thanks.  If I change the `env` variable from `template` to something custom (dev or demo), the playbooks don't run properly (namely haproxy provision). 

As seen in the `roles/haproxy/tasks/main.yml`  file:
```
- include: single-instance.yml
  when: env == 'vm' or env == 'test' or env == 'test2' or env == 'template'
```

Any suggestions without having to change the actual playbook code?  

Thanks!

**Comment by thijskh** [comment]
The difference between those list of environments and the "others" is that the others have a more complex haproxy setup where each app gets its own haproxy instance. It should not fail if you do so, but it is less simple.

If you want to keep to the single-instance setup currently I think the only way to achieve that is to indeed add an `or env == 'demo` to that task.
