### ISSUE TITLE
Ansible Installation of the OpenConext environment (VOOT branch)

### ISSUE THREAD

**Issue by mehdiHached** [OpenConext/OpenConext-deploy#9]
After launching the insatllation command below it fails on the error listed here after:
$ ./ansible-vm openconext-php.yml
----

failed: [145.100.180.77] => {"changed": true, "cmd": ["./bin/migrate"], "delta": "0:00:00.021347", "end": "2015-02-19 14:43:51.841312", "rc": 127, "start": "2015-02-19 14:43:51.819965", "stdout_lines": [], "warnings": []}
stderr: /usr/bin/env: php: No such file or directory

FATAL: all hosts have already failed -- aborting

**Comment by hanswesterbeek** [comment]
We established the fact that this was caused by you not using Vagrant. If you don't use vagrant, you have to run:

`./ansible-vm openconext-vm.yml`

This command is usually run by vagrant itself when you execute 'vagrant up'. See ./Vagrantfile.
